import React, { useState, useEffect } from 'react'
import { format } from 'date-fns'
import { pl } from 'date-fns/locale'
import { generateCMR } from '@/lib/utils/generateCMR'
import { Truck, Package, MapPin, Phone, FileText, Calendar, DollarSign, User, Clipboard, ArrowRight, ChevronDown, ChevronUp, AlertCircle, Edit, Pencil, Building, ShoppingBag, Weight, Bot, Link as LinkIcon } from 'lucide-react'
import { buildRoutePoints, calculateRouteDistance } from '@/app/services/calculateRoute'

export default function SpedycjaList({
  zamowienia,
  showArchive,
  isAdmin,
  onResponse,
  onMarkAsCompleted,
  onCreateOrder,
  canSendOrder,
  canCMR,
  onEdit,
  currentUserEmail
}) {
  const [expandedId, setExpandedId] = useState(null)
  const [routeDistances, setRouteDistances] = useState({})

  const buttonClasses = {
    primary: "px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors flex items-center gap-2",
    outline: "px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-100 transition-colors flex items-center gap-2",
    success: "px-4 py-2 bg-green-500 text-white rounded-md hover:bg-green-600 transition-colors flex items-center gap-2"
  }

  const formatAddress = (address) => {
    if (!address) return ''
    return `${address.city}, ${address.postalCode}, ${address.street}`
  }

  const formatDate = (dateString) => {
    if (!dateString) return 'Brak daty';
    try {
      return format(new Date(dateString), 'dd.MM.yyyy', { locale: pl });
    } catch (error) {
      console.error("Błąd formatowania daty:", error, dateString);
      return 'Nieprawidłowa data';
    }
  }

  const getLoadingCity = (zamowienie) => {
    if (zamowienie.location === 'Odbiory własne' && zamowienie.producerAddress) {
      return zamowienie.producerAddress.city || '';
    } else if (zamowienie.location === 'Magazyn Białystok') {
      return 'Białystok';
    } else if (zamowienie.location === 'Magazyn Zielonka') {
      return 'Zielonka';
    }
    return '';
  }

  const getDeliveryCity = (zamowienie) => {
    return zamowienie.delivery?.city || '';
  }

  // Funkcja do generowania linku do Google Maps
  const generateGoogleMapsLink = (transport) => {
    // Pobierz dane źródłowe i docelowe
    let origin = '';
    let destination = '';

    // Ustal miejsce załadunku
    if (transport.location === 'Odbiory własne' && transport.producerAddress) {
      const addr = transport.producerAddress;
      origin = `${addr.city},${addr.postalCode},${addr.street || ''}`;
    } else if (transport.location === 'Magazyn Białystok') {
      origin = 'Białystok';
    } else if (transport.location === 'Magazyn Zielonka') {
      origin = 'Zielonka';
    }

    // Ustal miejsce dostawy
    if (transport.delivery) {
      const addr = transport.delivery;
      destination = `${addr.city},${addr.postalCode},${addr.street || ''}`;
    }

    // Jeśli brakuje któregoś z punktów, zwróć pusty string
    if (!origin || !destination) return '';

    // Kodowanie URI komponentów
    origin = encodeURIComponent(origin);
    destination = encodeURIComponent(destination);

    // Zwróć link do Google Maps
    return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=driving`;
  };

  // FUNKCJA: Sprawdza czy odpowiedź została wygenerowana automatycznie
  const isAutoGeneratedResponse = (zamowienie) => {
    return zamowienie.response && zamowienie.response.autoGenerated === true;
  };

  // Funkcja pomocnicza: Generuje link Google Maps dla całej trasy połączonej
  const generateGoogleMapsLinkForRoute = (routePoints) => {
    if (!routePoints || routePoints.length < 2) return '';
    const origin = encodeURIComponent(routePoints[0]);
    const destination = encodeURIComponent(routePoints[routePoints.length - 1]);
    const intermediate = routePoints.slice(1, -1);
    const waypointsParam = intermediate.length > 0
      ? `&waypoints=${intermediate.map(p => encodeURIComponent(p)).join('|')}`
      : '';
    return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}${waypointsParam}&travelmode=driving`;
  };

  // FUNKCJA: Pobiera pełne informacje o grupie transportu połączonego
  const getConnectedGroupInfo = (transport) => {
    if (!transport?.response) return null;

    const resp = transport.response;
    const isAuto = Boolean(resp.autoGenerated);
    const sourceId = resp.sourceTransportId;

    // 1. Zlecenie wtórne (auto-wygenerowane z sourceTransportId)
    if (isAuto && sourceId) {
      const mainTransport = (zamowienia || []).find(t => String(t.id) === String(sourceId));

      const connectedTransports = mainTransport?.response?.connectedTransports
        || resp.connectedTransports
        || [];

      const mainId = sourceId;
      const mainOrderNumber = mainTransport?.orderNumber
        || mainTransport?.order_number
        || resp.mainTransportOrderNumber
        || `ID: ${mainId}`;
      const mainStart = mainTransport ? getLoadingCity(mainTransport) : (resp.mainTransportRoute?.split(' → ')[0] || '');
      const mainEnd = mainTransport ? getDeliveryCity(mainTransport) : (resp.mainTransportRoute?.split(' → ')[1] || '');
      const mainRoute = mainTransport ? `${mainStart} → ${mainEnd}` : (resp.mainTransportRoute || '');
      const mainMpk = mainTransport ? getCurrentMPK(mainTransport) : (resp.mainTransportMpk || '');
      const mainDistance = mainTransport ? (mainTransport.distanceKm || mainTransport.distance_km || 0) : (resp.mainTransportDistanceKm || 0);

      const totalPrice = mainTransport?.response?.totalDeliveryPrice
        || mainTransport?.response?.deliveryPrice
        || resp.totalDeliveryPrice
        || resp.deliveryPrice;
      const costPerTransport = mainTransport?.response?.costPerTransport
        || resp.costPerTransport
        || resp.deliveryPrice;
      const totalDistance = mainTransport?.response?.totalDistance
        || resp.mainTransportTotalDistance
        || resp.totalDistance
        || null;

      return {
        isSecondary: true,
        currentTransportId: transport.id,
        mainTransportId: mainId,
        mainTransport: {
          id: mainId,
          orderNumber: mainOrderNumber,
          route: mainRoute,
          startCity: mainStart,
          endCity: mainEnd,
          mpk: mainMpk,
          distanceKm: mainDistance
        },
        connectedTransports,
        totalPrice,
        costPerTransport,
        totalDistance,
        totalCount: connectedTransports.length + 1
      };
    }

    // 2. Zlecenie główne (posiada connectedTransports z elementami)
    if (resp.connectedTransports && resp.connectedTransports.length > 0) {
      const connectedTransports = resp.connectedTransports;
      const totalPrice = resp.totalDeliveryPrice || resp.deliveryPrice;
      const costPerTransport = resp.costPerTransport
        || (totalPrice && connectedTransports.length > 0 ? (Number(totalPrice) / (connectedTransports.length + 1)).toFixed(2) : null);

      const mainStart = getLoadingCity(transport);
      const mainEnd = getDeliveryCity(transport);
      const totalDistance = resp.totalDistance || null;

      return {
        isSecondary: false,
        currentTransportId: transport.id,
        mainTransportId: transport.id,
        mainTransport: {
          id: transport.id,
          orderNumber: transport.orderNumber || transport.order_number,
          route: `${mainStart} → ${mainEnd}`,
          startCity: mainStart,
          endCity: mainEnd,
          mpk: getCurrentMPK(transport),
          distanceKm: transport.distanceKm || transport.distance_km || 0
        },
        connectedTransports,
        totalPrice,
        costPerTransport,
        totalDistance,
        totalCount: connectedTransports.length + 1
      };
    }

    return null;
  };

  // Oblicza całkowitą trasę dla połączonych transportów
  const calculateConnectedRoute = (transport) => {
    const group = getConnectedGroupInfo(transport);
    if (!group) return null;

    const { mainTransport, connectedTransports } = group;
    const enrichedConnected = connectedTransports.map(ct => {
      if (ct.startAddress && ct.endAddress) return ct;
      const full = (zamowienia || []).find(t => String(t.id) === String(ct.id));
      if (!full) return ct;
      return {
        ...ct,
        startAddress: full.location === 'Odbiory własne' ? full.producerAddress : (ct.startAddress || { city: full.location?.replace(/^magazyn\s+/i, '') }),
        endAddress: full.delivery || ct.endAddress
      };
    });

    const routePoints = buildRoutePoints(mainTransport, enrichedConnected);
    const routeKey = routePoints.length > 0 ? routePoints.join(' → ') : (mainTransport.route || '');

    // 1. Sprawdź, czy zapisany jest rzeczywisty dystans trasy łączonej punkt-do-punktu
    let totalDistance = group.totalDistance 
      || mainTransport.response?.totalDistance 
      || transport.response?.totalDistance 
      || routeDistances[routeKey] 
      || null;

    // 2. Jeśli nie ma jeszcze zapisanego dystansu w pamięci, bezpieczny fallback na bazie zlecenia głównego
    if (!totalDistance) {
      totalDistance = Number(mainTransport.distanceKm) || 0;
    }

    return {
      route: routeKey,
      totalDistance: Number(totalDistance),
      connectedCount: connectedTransports.length,
      routePoints
    };
  };

  // Efekt do asynchronicznego dociągania dystansów dla tras łączonych bez zapisanego totalDistance
  useEffect(() => {
    if (!zamowienia || zamowienia.length === 0) return;

    zamowienia.forEach(z => {
      const group = getConnectedGroupInfo(z);
      if (group && group.connectedTransports && group.connectedTransports.length > 0) {
        const points = buildRoutePoints(group.mainTransport, group.connectedTransports);
        const routeKey = points.join(' → ');

        if (!group.totalDistance && !routeDistances[routeKey] && points.length >= 2) {
          calculateRouteDistance(points)
            .then(res => {
              if (res && res.success && res.totalDistanceKm > 0) {
                setRouteDistances(prev => ({
                  ...prev,
                  [routeKey]: res.totalDistanceKm
                }));
              }
            })
            .catch(err => {
              console.warn('[SpedycjaList] Błąd kalkulacji dystansu trasy:', err);
            });
        }
      }
    });
  }, [zamowienia, routeDistances]);

  // FUNKCJA POMOCNICZA: Pobiera nazwę firmy załadowczej
  const getLoadingCompanyName = (transport) => {
    if (transport.location === 'Odbiory własne' && transport.sourceClientName) {
      return transport.sourceClientName;
    } else if (transport.location === 'Magazyn Białystok') {
      return 'Magazyn Białystok';
    } else if (transport.location === 'Magazyn Zielonka') {
      return 'Magazyn Zielonka';
    }
    return ''; // Nie wyświetlamy numeru telefonu, zostawiamy puste
  };

  // FUNKCJA POMOCNICZA: Pobiera nazwę klienta docelowego (budowy lub firmy)
  const getUnloadingCompanyName = (zamowienie) => {
    if (zamowienie.responsibleConstructions && zamowienie.responsibleConstructions.length > 0) {
      return zamowienie.responsibleConstructions[0].name;
    }
    return zamowienie.clientName || 'Odbiorca nieznany';
  };

  // FUNKCJA POMOCNICZA: Pobiera trasę dla wyświetlenia w nagłówku
  const getDisplayRoute = (zamowienie) => {
    const connectedRoute = calculateConnectedRoute(zamowienie);

    if (connectedRoute) {
      return {
        text: connectedRoute.route,
        distance: connectedRoute.totalDistance,
        isConnected: true
      };
    }

    // Dla normalnych transportów
    return {
      text: `${getLoadingCity(zamowienie)} → ${getDeliveryCity(zamowienie)}`,
      distance: zamowienie.distanceKm || 0,
      isConnected: false
    };
  };

  // Funkcja do określania statusu zamówienia - ZMODYFIKOWANA
  const getStatusLabel = (zamowienie) => {
    if (zamowienie.status === 'completed') {
      return {
        label: 'Zakończone',
        className: 'bg-green-100 text-green-800 border border-green-300',
        icon: <Clipboard size={16} className="mr-1" />
      };
    } else if (zamowienie.response && Object.keys(zamowienie.response).length > 0) {
      // Wszystkie odpowiedzi teraz mają ten sam status "Odpowiedziane"
      return {
        label: 'Odpowiedziane',
        className: 'bg-yellow-100 text-yellow-800 border border-yellow-300',
        icon: <Truck size={16} className="mr-1" />
      };
    } else {
      return {
        label: 'Nowe',
        className: 'bg-blue-100 text-blue-800 border border-blue-300',
        icon: <Package size={16} className="mr-1" />
      };
    }
  }

  // Funkcja sprawdzająca czy data dostawy została zmieniona
  const isDeliveryDateChanged = (zamowienie) => {
    return zamowienie.response &&
      zamowienie.response.dateChanged === true &&
      zamowienie.response.newDeliveryDate;
  }

  // Funkcja pobierająca aktualną datę dostawy (oryginalną lub zmienioną)
  const getActualDeliveryDate = (zamowienie) => {
    if (isDeliveryDateChanged(zamowienie)) {
      return zamowienie.response.newDeliveryDate;
    }
    return zamowienie.deliveryDate;
  }

  // Sprawdza, czy bieżący użytkownik jest twórcą zamówienia
  const isCreatedByCurrentUser = (zamowienie) => {
    return zamowienie.createdByEmail === currentUserEmail;
  }

  // Sprawdza, czy zamówienie może być edytowane
  const canBeEdited = (zamowienie) => {
    // Tylko nowe zamówienia bez odpowiedzi mogą być edytowane
    return (zamowienie.status === 'new' || zamowienie.status === 'responded') &&
      (!zamowienie.response || Object.keys(zamowienie.response).length === 0);
  }

  // Funkcja pobierająca poprawne MPK (z zamówienia lub z powiązanej budowy)
  const getCurrentMPK = (zamowienie) => {
    if (zamowienie.responsibleConstructions && zamowienie.responsibleConstructions.length > 0) {
      return zamowienie.responsibleConstructions[0].mpk || zamowienie.mpk || '';
    }
    return zamowienie.mpk || '';
  }

  // Renderuje info o powiązanych transportach
  const renderConnectedTransports = (transport) => {
    const group = getConnectedGroupInfo(transport);
    if (!group) return null;

    const { currentTransportId, mainTransport, connectedTransports, totalPrice, costPerTransport } = group;
    const connectedRoute = calculateConnectedRoute(transport);
    const gmapsLink = connectedRoute?.routePoints ? generateGoogleMapsLinkForRoute(connectedRoute.routePoints) : '';

    return (
      <div className="mt-4 p-4 bg-indigo-50 border border-indigo-200 rounded-lg shadow-xs">
        <div className="flex items-center justify-between mb-3">
          <h4 className="font-semibold text-indigo-900 flex items-center text-sm md:text-base">
            <LinkIcon size={18} className="mr-2 text-indigo-600" />
            Transport połączony
          </h4>
          <span className="text-xs font-semibold px-2.5 py-1 bg-indigo-100 text-indigo-800 rounded-full border border-indigo-200">
            {connectedTransports.length + 1} zlecenia w trasie
          </span>
        </div>

        {/* Pokaż pełną trasę */}
        {connectedRoute && (
          <div className="mb-3 p-3 bg-white rounded-md border border-indigo-200 shadow-xs">
            <div className="text-sm font-semibold text-indigo-900 flex items-center flex-wrap gap-1">
              <span className="text-indigo-600 font-normal">Trasa połączona:</span> {connectedRoute.route}
            </div>
            <div className="text-xs text-indigo-600 mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1">
              {connectedRoute.totalDistance > 0 && (
                <span>Łączna odległość: <strong>{connectedRoute.totalDistance} km</strong></span>
              )}
              <span>Liczba zleceń w trasie: <strong>{connectedTransports.length + 1}</strong></span>
              {gmapsLink && (
                <a
                  href={gmapsLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-800 hover:underline flex items-center font-medium ml-auto"
                  onClick={(e) => e.stopPropagation()}
                >
                  <MapPin size={12} className="mr-1" />
                  Pokaż całą trasę na mapie
                </a>
              )}
            </div>
          </div>
        )}

        {/* Lista zleceń w tej trasie */}
        <div className="text-xs font-semibold uppercase tracking-wider text-indigo-700 mb-2">
          Zlecenia w tej trasie:
        </div>
        <div className="space-y-2">
          {connectedTransports.map((ct, index) => {
            const isCurrent = String(ct.id) === String(currentTransportId);
            return (
              <div
                key={ct.id || index}
                className={`p-2.5 rounded-md border transition-colors flex justify-between items-center text-sm ${
                  isCurrent
                    ? 'bg-blue-50/90 border-blue-400 ring-1 ring-blue-400'
                    : 'bg-white border-indigo-100'
                }`}
              >
                <div className="flex-1 min-w-0 pr-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-gray-900">
                      {index + 1}. {ct.orderNumber || ct.id}
                    </span>
                    {ct.route && (
                      <span className="text-xs text-gray-600 font-normal">
                        ({ct.route})
                      </span>
                    )}
                    {isCurrent && (
                      <span className="text-[11px] font-semibold bg-blue-600 text-white px-2 py-0.5 rounded-full">
                        Bieżące zlecenie
                      </span>
                    )}
                  </div>
                  <div className="text-xs text-indigo-800 mt-1 flex flex-wrap items-center gap-x-2 gap-y-1">
                    <span className={`px-1.5 py-0.5 rounded text-[11px] font-medium ${
                      ct.type === 'loading' ? 'bg-amber-100 text-amber-800' : 'bg-green-100 text-green-800'
                    }`}>
                      {ct.type === 'loading' ? 'Załadunek' : 'Rozładunek'}
                    </span>
                    {ct.mpk && <span>MPK: <strong>{ct.mpk}</strong></span>}
                    {ct.responsiblePerson && <span>Osoba: <strong>{ct.responsiblePerson}</strong></span>}
                  </div>
                </div>
              </div>
            );
          })}

          {/* Główny transport w liście */}
          {mainTransport && (
            <div
              className={`p-2.5 rounded-md border transition-colors flex justify-between items-center text-sm ${
                String(mainTransport.id) === String(currentTransportId)
                  ? 'bg-blue-50/90 border-blue-400 ring-1 ring-blue-400'
                  : 'bg-indigo-100/70 border-indigo-200'
              }`}
            >
              <div className="flex-1 min-w-0 pr-2">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="font-semibold text-indigo-950">
                    {connectedTransports.length + 1}. {mainTransport.orderNumber || mainTransport.id}
                  </span>
                  {mainTransport.route && (
                    <span className="text-xs text-indigo-800 font-normal">
                      ({mainTransport.route})
                    </span>
                  )}
                  <span className="text-[11px] font-semibold bg-indigo-200 text-indigo-800 px-1.5 py-0.5 rounded">
                    Zlecenie główne
                  </span>
                  {String(mainTransport.id) === String(currentTransportId) && (
                    <span className="text-[11px] font-semibold bg-blue-600 text-white px-2 py-0.5 rounded-full">
                      Bieżące zlecenie
                    </span>
                  )}
                </div>
                <div className="text-xs text-indigo-800 mt-1 flex flex-wrap items-center gap-x-2 gap-y-1">
                  {mainTransport.mpk && <span>MPK: <strong>{mainTransport.mpk}</strong></span>}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Informacje finansowe */}
        {(totalPrice || costPerTransport) && (
          <div className="text-sm text-indigo-900 mt-3 pt-3 border-t border-indigo-200/80 flex flex-wrap justify-between items-center gap-2">
            <div>
              {totalPrice && (
                <div>
                  <span className="text-indigo-600 text-xs uppercase font-medium mr-1">Całkowity koszt trasy:</span>
                  <span className="font-bold text-indigo-950">{totalPrice} PLN</span>
                </div>
              )}
            </div>
            {costPerTransport && (
              <div className="text-xs bg-white px-2.5 py-1 rounded border border-indigo-200 text-indigo-900 font-medium">
                Koszt przypisany / zlecenie: <strong>{costPerTransport} PLN</strong>
              </div>
            )}
          </div>
        )}
      </div>
    );
  };

  // Renderuje info o odpowiedzialnych budowach
  const renderResponsibleConstructions = (transport) => {
    if (!transport.responsibleConstructions || !transport.responsibleConstructions.length) return null;

    return (
      <div className="mt-2">
        <div className="font-medium text-sm">Budowy:</div>
        <div className="flex flex-wrap gap-2 mt-1">
          {transport.responsibleConstructions.map(construction => (
            <div key={construction.id} className="bg-green-50 text-green-700 px-2 py-1 rounded-md text-xs flex items-center">
              <Building size={12} className="mr-1" />
              {construction.name}
              <span className="ml-1 text-green-600">({construction.mpk})</span>
            </div>
          ))}
        </div>
      </div>
    );
  };

  // Renderuje info o towarze
  const renderGoodsInfo = (transport) => {
    if (!transport.goodsDescription) return null;

    return (
      <div className="mt-3 bg-blue-50 p-2 rounded-md border border-blue-100">
        <div className="flex items-center text-blue-700 font-medium">
          <ShoppingBag size={14} className="mr-1" />
          Towar
        </div>
        {transport.goodsDescription.description && (
          <p className="text-sm mt-1">{transport.goodsDescription.description}</p>
        )}
        {transport.goodsDescription.weight && (
          <p className="text-sm flex items-center mt-1">
            <Weight size={12} className="mr-1" />
            Waga: {transport.goodsDescription.weight}
          </p>
        )}
      </div>
    );
  };

  return (
    <div className="divide-y">
      {zamowienia
        .filter(z => showArchive ? z.status === 'completed' : (z.status === 'new' || z.status === 'responded'))
        .map((zamowienie) => {
          const statusInfo = getStatusLabel(zamowienie);
          const dateChanged = isDeliveryDateChanged(zamowienie);
          const displayDate = getActualDeliveryDate(zamowienie);
          const canEdit = canBeEdited(zamowienie) && (isAdmin || isCreatedByCurrentUser(zamowienie));
          const isAutoResponse = isAutoGeneratedResponse(zamowienie);
          const displayRoute = getDisplayRoute(zamowienie);

          return (
            <div key={zamowienie.id} className="p-4 hover:bg-gray-50 transition-colors">
              <div
                onClick={() => setExpandedId(expandedId === zamowienie.id ? null : zamowienie.id)}
                className="flex justify-between items-start cursor-pointer"
              >
                <div className="flex items-start">
                  <div className="mr-3 mt-1">
                    <div className={`h-8 w-8 rounded-full flex items-center justify-center text-blue-700 ${isAutoResponse ? 'bg-purple-100' : 'bg-blue-100'
                      }`}>
                      {isAutoResponse ? <Bot size={18} /> : <Truck size={18} />}
                    </div>
                  </div>
                  <div>
                    <h3 className="font-medium flex items-center flex-wrap gap-2">
                      <div className="flex items-center mt-1 mb-1">
                        <div className="flex flex-col">
                          <span>{getLoadingCity(zamowienie)}</span>
                          <span className="text-[11px] text-gray-500 font-normal leading-tight mt-0.5">{getLoadingCompanyName(zamowienie)}</span>
                        </div>
                        <span className="mx-3 text-gray-400">&rarr;</span>
                        <div className="flex flex-col">
                          <span>{getDeliveryCity(zamowienie)}</span>
                          <span className="text-[11px] text-gray-500 font-normal leading-tight mt-0.5">{getUnloadingCompanyName(zamowienie)}</span>
                        </div>
                      </div>

                      {displayRoute.isConnected && (
                        <span className="bg-indigo-100 text-indigo-800 px-2 py-0.5 rounded-full text-xs flex items-center h-6 font-medium border border-indigo-200">
                          <LinkIcon size={12} className="mr-1 text-indigo-600" />
                          Połączone ({displayRoute.distance} km)
                        </span>
                      )}
                    </h3>
                    <p className="text-sm text-gray-500 flex items-center mt-1">
                      <Calendar size={14} className="mr-1" />
                      Data dostawy:
                      {dateChanged ? (
                        <span className="ml-1 flex items-center">
                          <span className="line-through text-gray-400">{formatDate(zamowienie.deliveryDate)}</span>
                          <ArrowRight size={12} className="mx-1 text-yellow-500" />
                          <span className="bg-yellow-50 px-1.5 py-0.5 rounded text-yellow-700 font-medium">
                            {formatDate(displayDate)}
                          </span>
                        </span>
                      ) : (
                        <span className="ml-1">{formatDate(displayDate)}</span>
                      )}
                    </p>
                    <p className="text-sm text-gray-500 flex items-center mt-1">
                      <FileText size={14} className="mr-1" />
                      {zamowienie.orderNumber && <span className="font-medium mr-2">{zamowienie.orderNumber}</span>}
                      MPK: {getCurrentMPK(zamowienie)}
                    </p>

                    {/* Wyświetl informację o budowach */}
                    {zamowienie.responsibleConstructions && zamowienie.responsibleConstructions.length > 0 && (
                      <div className="flex items-center mt-1">
                        <Building size={14} className="mr-1 text-green-600" />
                        <span className="text-sm text-green-600">
                          Budowa: {zamowienie.responsibleConstructions[0].name}
                          {zamowienie.responsibleConstructions.length > 1 && ` +${zamowienie.responsibleConstructions.length - 1}`}
                        </span>
                      </div>
                    )}
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <span className={`px-3 py-1 rounded-full text-sm flex items-center ${statusInfo.className}`}>
                    {statusInfo.icon}
                    {statusInfo.label}
                  </span>

                  {expandedId === zamowienie.id ? (
                    <button
                      className="p-1 rounded-full hover:bg-gray-200"
                      onClick={(e) => {
                        e.stopPropagation()
                        setExpandedId(null)
                      }}
                    >
                      <ChevronUp size={20} />
                    </button>
                  ) : (
                    <button
                      className="p-1 rounded-full hover:bg-gray-200"
                      onClick={(e) => {
                        e.stopPropagation()
                        setExpandedId(zamowienie.id)
                      }}
                    >
                      <ChevronDown size={20} />
                    </button>
                  )}

                  {/* Przycisk edycji - widoczny dla twórcy lub admina */}
                  {canEdit && (
                    <button
                      type="button"
                      className={buttonClasses.outline}
                      onClick={(e) => {
                        e.stopPropagation()
                        onEdit(zamowienie)
                      }}
                    >
                      <Pencil size={16} />
                      Edytuj
                    </button>
                  )}

                  {/* Przyciski admina - odpowiadanie i oznaczanie jako zrealizowane */}
                  {isAdmin && (zamowienie.status === 'new' || zamowienie.status === 'responded') && (
                    <>
                      {/* Pokaż przycisk "Odpowiedz" tylko jeśli NIE MA odpowiedzi */}
                      {(!zamowienie.response || Object.keys(zamowienie.response).length === 0) && (
                        <button
                          type="button"
                          className={buttonClasses.outline}
                          onClick={(e) => {
                            e.stopPropagation()
                            onResponse(zamowienie)
                          }}
                        >
                          <Clipboard size={16} />
                          Odpowiedz
                        </button>
                      )}

                      {/* Pokaż przycisk "Edytuj odpowiedź" tylko jeśli JUŻ MA odpowiedź */}
                      {(zamowienie.response && Object.keys(zamowienie.response).length > 0) && (
                        <button
                          type="button"
                          className={buttonClasses.outline}
                          onClick={(e) => {
                            e.stopPropagation()
                            onResponse(zamowienie)
                          }}
                        >
                          <Edit size={16} />
                          Edytuj odpowiedź
                        </button>
                      )}

                      <button
                        type="button"
                        className={buttonClasses.success}
                        onClick={(e) => {
                          e.stopPropagation()
                          if (confirm('Czy na pewno chcesz oznaczyć to zlecenie jako zrealizowane?')) {
                            onMarkAsCompleted(zamowienie.id)
                          }
                        }}
                      >
                        <Truck size={16} />
                        Zrealizowane
                      </button>
                    </>
                  )}
                </div>
              </div>

              {expandedId === zamowienie.id && (
                <div className="mt-6 pl-4 border-l-4 border-blue-200 animate-fadeIn">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-4">
                    {/* Sekcja 1: Dane zamówienia i zamawiającego */}
                    <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
                      <h4 className="font-medium mb-3 pb-2 border-b flex items-center text-blue-700">
                        <FileText size={18} className="mr-2" />
                        Dane zamówienia
                      </h4>
                      <p className="text-sm mb-2"><span className="font-medium">Numer zamówienia:</span> {zamowienie.orderNumber || '-'}</p>
                      <p className="text-sm mb-2"><span className="font-medium">MPK:</span> {getCurrentMPK(zamowienie)}</p>
                      <p className="text-sm mb-2"><span className="font-medium">Osoba dodająca:</span> {zamowienie.createdBy || zamowienie.requestedBy}</p>
                      <p className="text-sm mb-2"><span className="font-medium">Osoba odpowiedzialna:</span> {zamowienie.responsiblePerson || zamowienie.createdBy || zamowienie.requestedBy}</p>
                      <p className="text-sm mb-2"><span className="font-medium">Dokumenty:</span> {zamowienie.documents}</p>

                      {/* Dodana informacja o nazwie klienta/odbiorcy */}
                      {zamowienie.clientName && (
                        <p className="text-sm mb-2"><span className="font-medium">Nazwa klienta/odbiorcy:</span> {zamowienie.clientName}</p>
                      )}

                      {/* Informacje o budowach */}
                      {renderResponsibleConstructions(zamowienie)}

                      {/* Informacja o towarze */}
                      {renderGoodsInfo(zamowienie)}
                    </div>

                    {/* Sekcja 2: Szczegóły załadunku/dostawy */}
                    <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
                      <h4 className="font-medium mb-3 pb-2 border-b flex items-center text-green-700">
                        <MapPin size={18} className="mr-2" />
                        Szczegóły załadunku
                      </h4>
                      {zamowienie.location === 'Odbiory własne' ? (
                        <p className="mb-2">{formatAddress(zamowienie.producerAddress)}</p>
                      ) : (
                        <p className="mb-2">{zamowienie.location}</p>
                      )}
                      <p className="text-sm text-gray-600 mb-3 flex items-center">
                        <Phone size={14} className="mr-1" />
                        Kontakt: {zamowienie.loadingContact}
                      </p>

                      <h4 className="font-medium mt-5 mb-3 pb-2 border-b flex items-center text-orange-700">
                        <MapPin size={18} className="mr-2" />
                        Szczegóły dostawy
                      </h4>
                      <p className="mb-2">{formatAddress(zamowienie.delivery)}</p>
                      <p className="text-sm text-gray-600 mb-3 flex items-center">
                        <Phone size={14} className="mr-1" />
                        Kontakt: {zamowienie.unloadingContact}
                      </p>

                      {/* Link do Google Maps */}
                      {generateGoogleMapsLink(zamowienie) && (
                        <div className="mt-4">
                          <a
                            href={generateGoogleMapsLink(zamowienie)}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-blue-50 hover:bg-blue-100 text-blue-700 px-3 py-2 rounded-md flex items-center w-fit transition-colors"
                            onClick={(e) => e.stopPropagation()}
                          >
                            <MapPin size={16} className="mr-2" />
                            Zobacz trasę na Google Maps
                          </a>
                        </div>
                      )}
                    </div>

                    {/* Sekcja 3: Informacje o transporcie */}
                    <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
                      <h4 className="font-medium mb-3 pb-2 border-b flex items-center text-purple-700">
                        <Truck size={18} className="mr-2" />
                        Informacje o transporcie
                      </h4>

                      {/* Data dostawy z wyróżnieniem, jeśli zmieniona */}
                      <div className="text-sm mb-2">
                        <div className="flex items-center">
                          <Calendar size={14} className="mr-2 text-gray-500" />
                          <span className="font-medium">Data dostawy:</span>
                        </div>

                        {dateChanged ? (
                          <div className="ml-7 mt-1 p-2 bg-yellow-50 rounded-md border border-yellow-200">
                            <div className="flex items-center text-yellow-800">
                              <AlertCircle size={14} className="mr-1" />
                              <span className="font-medium">Uwaga: Data została zmieniona!</span>
                            </div>
                            <div className="mt-1 flex items-center">
                              <span className="text-gray-500">Data pierwotna:</span>
                              <span className="ml-1 line-through text-gray-500">{formatDate(zamowienie.deliveryDate)}</span>
                            </div>
                            <div className="mt-1 flex items-center">
                              <span className="text-gray-800 font-medium">Data aktualna:</span>
                              <span className="ml-1 font-medium text-green-700">{formatDate(zamowienie.response.newDeliveryDate)}</span>
                            </div>
                          </div>
                        ) : (
                          <div className="ml-7 mt-1">
                            {formatDate(zamowienie.deliveryDate)}
                          </div>
                        )}
                      </div>

                      <p className="text-sm mb-2 flex items-center">
                        <Calendar size={14} className="mr-2 text-gray-500" />
                        <span className="font-medium">Data dodania:</span> {formatDate(zamowienie.createdAt)}
                      </p>

                      <p className="text-sm mb-2 flex items-center">
                        <MapPin size={14} className="mr-2 text-gray-500" />
                        <span className="font-medium">Odległość:</span>
                        <span className="bg-blue-50 px-2 py-0.5 rounded ml-1 font-medium">
                          {displayRoute.isConnected
                            ? `${displayRoute.distance} km (trasa połączona)`
                            : `${displayRoute.distance} km`}
                        </span>
                      </p>

                      {zamowienie.response && zamowienie.response.deliveryPrice && (
                        <>
                          <p className="text-sm mb-2 flex items-center">
                            <DollarSign size={14} className="mr-2 text-gray-500" />
                            <span className="font-medium">Cena transportu:</span>
                            <span className="bg-green-50 px-2 py-0.5 rounded ml-1 font-medium">
                              {zamowienie.response.deliveryPrice} PLN
                            </span>
                          </p>
                          <p className="text-sm mb-2 flex items-center">
                            <DollarSign size={14} className="mr-2 text-gray-500" />
                            <span className="font-medium">Cena za km:</span>
                            <span className="bg-green-50 px-2 py-0.5 rounded ml-1 font-medium">
                              {(() => {
                                const totalDistance = displayRoute.distance;
                                return totalDistance > 0
                                  ? (zamowienie.response.deliveryPrice / totalDistance).toFixed(2)
                                  : '0.00';
                              })()} PLN/km
                            </span>
                          </p>
                        </>
                      )}

                      {zamowienie.notes && (
                        <div className="mt-3 bg-gray-50 p-2 rounded-md">
                          <p className="text-sm"><span className="font-medium">Uwagi:</span> {zamowienie.notes}</p>
                        </div>
                      )}
                    </div>
                  </div>

                  {canEdit && (
                    <div className="mt-4 flex justify-end">
                      <button
                        type="button"
                        className={buttonClasses.primary}
                        onClick={(e) => {
                          e.stopPropagation()
                          onEdit(zamowienie)
                        }}
                      >
                        <Pencil size={16} />
                        Edytuj zamówienie
                      </button>
                    </div>
                  )}

                  {zamowienie.response && (
                    <div className={`mt-4 p-5 rounded-lg border shadow-sm ${isAutoResponse
                      ? 'bg-purple-50 border-purple-200'
                      : 'bg-gray-50 border-gray-200'
                      }`}>
                      <h4 className="font-medium mb-3 pb-2 border-b border-gray-200 flex items-center text-gray-800">
                        {isAutoResponse ? <Bot size={18} className="mr-2" /> : <Truck size={18} className="mr-2" />}
                        {isAutoResponse ? 'Szczegóły realizacji (transport połączony)' : 'Szczegóły realizacji'}
                      </h4>

                      {/* Renderuj informacje o powiązanych transportach */}
                      {renderConnectedTransports(zamowienie)}

                      {zamowienie.response.completedManually ? (
                        <div className="bg-blue-50 text-blue-800 p-3 rounded-md border border-blue-100 flex items-center">
                          <Clipboard size={18} className="mr-2" />
                          Zamówienie zostało ręcznie oznaczone jako zrealizowane.
                        </div>
                      ) : (
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                          {/* Informacje o przewoźniku */}
                          <div className="bg-white p-3 rounded-md shadow-sm border border-gray-100">
                            <h5 className="text-sm font-medium mb-2 pb-1 border-b flex items-center text-blue-600">
                              <User size={14} className="mr-1" />
                              Dane przewoźnika
                            </h5>
                            <p className="text-sm mb-1.5"><span className="font-medium">Kierowca:</span> {zamowienie.response.driverName} {zamowienie.response.driverSurname}</p>
                            <p className="text-sm mb-1.5"><span className="font-medium">Telefon:</span> {zamowienie.response.driverPhone}</p>
                            <p className="text-sm mb-1.5"><span className="font-medium">Numery auta:</span> {zamowienie.response.vehicleNumber}</p>
                            {zamowienie.response.transportType && (
                              <p className="text-sm mb-1.5"><span className="font-medium">Rodzaj transportu:</span> {zamowienie.response.transportType}</p>
                            )}
                          </div>

                          {/* Informacje o kosztach */}
                          <div className="bg-white p-3 rounded-md shadow-sm border border-gray-100">
                            <h5 className="text-sm font-medium mb-2 pb-1 border-b flex items-center text-green-600">
                              <DollarSign size={14} className="mr-1" />
                              Dane finansowe
                            </h5>
                            {zamowienie.response.totalDeliveryPrice ? (
                              <>
                                <p className="text-sm mb-1.5"><span className="font-medium">Koszt całej trasy:</span>
                                  <span className="bg-blue-50 px-2 py-0.5 rounded ml-1">
                                    {zamowienie.response.totalDeliveryPrice} PLN
                                  </span>
                                </p>
                                <p className="text-sm mb-1.5"><span className="font-medium">Koszt tego transportu:</span>
                                  <span className="bg-green-50 px-2 py-0.5 rounded ml-1">
                                    {zamowienie.response.deliveryPrice} PLN
                                  </span>
                                </p>
                              </>
                            ) : (
                              <p className="text-sm mb-1.5"><span className="font-medium">Cena całkowita:</span>
                                <span className="bg-green-50 px-2 py-0.5 rounded ml-1">
                                  {zamowienie.response.deliveryPrice} PLN
                                </span>
                              </p>
                            )}
                            <p className="text-sm mb-1.5"><span className="font-medium">Odległość całkowita:</span>
                              {`${displayRoute.distance} km${displayRoute.isConnected ? ' (łącznie)' : ''}`}
                            </p>
                            {(() => {
                              const totalDistance = displayRoute.distance;

                              if (totalDistance > 0 && zamowienie.response.deliveryPrice > 0) {
                                return (
                                  <p className="text-sm mb-1.5"><span className="font-medium">Koszt za km:</span>
                                    <span className="bg-green-50 px-2 py-0.5 rounded ml-1">
                                      {(zamowienie.response.deliveryPrice / totalDistance).toFixed(2)} PLN/km
                                    </span>
                                  </p>
                                );
                              }
                              return null;
                            })()}

                            {/* Podział kosztów dla połączonych transportów (stary system) */}
                            {isAutoResponse && zamowienie.response.costPerTransport && !zamowienie.response.totalDeliveryPrice && (
                              <div className="mt-2 pt-2 border-t border-gray-100">
                                <p className="text-sm text-blue-600">
                                  <span className="font-medium">Koszt na transport:</span>
                                  <span className="ml-1">{zamowienie.response.costPerTransport} PLN</span>
                                </p>
                                <p className="text-xs text-gray-500 mt-1">
                                  {(() => {
                                    const connectedRoute = calculateConnectedRoute(zamowienie);
                                    return connectedRoute ? `Podzielone na ${connectedRoute.connectedCount + 1} transporty` : '';
                                  })()}
                                </p>
                              </div>
                            )}
                          </div>

                          {/* Informacje o realizacji */}
                          <div className="bg-white p-3 rounded-md shadow-sm border border-gray-100">
                            <h5 className="text-sm font-medium mb-2 pb-1 border-b flex items-center text-purple-600">
                              <Calendar size={14} className="mr-1" />
                              Informacje o realizacji
                            </h5>
                            <p className="text-sm mb-1.5"><span className="font-medium">Data odpowiedzi:</span> {formatDate(zamowienie.completedAt || zamowienie.createdAt)}</p>

                            {/* Wyświetl informację o automatycznym generowaniu */}
                            {isAutoResponse && (
                              <div className="bg-purple-50 p-2 rounded-md border border-purple-100 mt-2 mb-1.5">
                                <p className="text-xs font-medium text-purple-800 flex items-center">
                                  <Bot size={12} className="mr-1" />
                                  Transport połączony
                                </p>
                              </div>
                            )}

                            {zamowienie.response.dateChanged && (
                              <div className="bg-yellow-50 p-2 rounded-md border border-yellow-100 mt-2 mb-1.5">
                                <p className="text-sm font-medium text-yellow-800">Zmieniono datę dostawy:</p>
                                <p className="text-xs flex justify-between mt-1">
                                  <span>Z: <span className="line-through">{formatDate(zamowienie.response.originalDeliveryDate)}</span></span>
                                  <span>→</span>
                                  <span>Na: <span className="font-medium">{formatDate(zamowienie.response.newDeliveryDate)}</span></span>
                                </p>
                              </div>
                            )}

                            {zamowienie.response.adminNotes && (
                              <p className="text-sm"><span className="font-medium">Uwagi:</span> {zamowienie.response.adminNotes}</p>
                            )}
                          </div>
                        </div>
                      )}

                      <div className="mt-5 flex space-x-3">
                        {canCMR && (
                          <button
                            type="button"
                            className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors flex items-center gap-2"
                            onClick={() => generateCMR(zamowienie)}
                          >
                            <FileText size={16} />
                            Generuj CMR
                          </button>
                        )}
                        {zamowienie.response && !showArchive && canSendOrder && (
                          <button
                            type="button"
                            className="px-4 py-2 bg-green-500 text-white rounded-md hover:bg-green-600 transition-colors flex items-center gap-2"
                            onClick={() => onCreateOrder(zamowienie)}
                          >
                            <Truck size={16} />
                            Stwórz zlecenie transportowe
                          </button>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
    </div>
  )
}
